[package]
name = "byte_counter"
description = "Timestamped byte counter"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"

[dependencies]
serde = "1.0.171"
serde_derive = "1.0.171"

[dev-dependencies]
rand = "0.8.5"
